export default {
  "title": "QR-Bolt",
  "description": "Generate customized QR codes with gradients, shapes, and center logos 100% locally and privately.",
  "seo_title": "QR-Bolt | Free Online Custom QR Code Generator with Logo",
  "seo_description": "Create custom QR codes with custom logos, gradient colors, and unique shapes. 100% client-side, free, and secure. Download in high-quality PNG or SVG.",
  "tabContent": "Content",
  "tabDesign": "Design",
  "tabLogo": "Logo Overlay",
  "labelMode": "QR Code Type",
  "modeUrl": "URL / Link",
  "modeText": "Plain Text",
  "modeWifi": "WiFi Network",
  "modeEmail": "Email Template",
  "modeSms": "SMS Message",
  "placeholderUrl": "Enter website URL (e.g., https://example.com)",
  "placeholderText": "Type your text message here...",
  "labelWifiSsid": "Network SSID (Name)",
  "labelWifiPassword": "Password",
  "labelWifiSecurity": "Security Type",
  "labelEmailAddress": "Recipient Email",
  "labelEmailSubject": "Subject Line",
  "labelEmailBody": "Email Body",
  "labelSmsNumber": "Phone Number",
  "labelSmsMessage": "SMS Body",
  "labelDotType": "Pattern Shape",
  "labelCornerType": "Outer Frame Shape",
  "labelCornerDotType": "Inner Dot Shape",
  "labelColorType": "Fill Type",
  "colorSolid": "Solid Color",
  "colorGradient": "Gradient Color",
  "labelMainColor": "Dots Color",
  "labelBgColor": "Background Color",
  "labelGradientType": "Gradient Style",
  "gradLinear": "Linear Gradient",
  "gradRadial": "Radial Gradient",
  "labelGradientColor1": "Start Color",
  "labelGradientColor2": "End Color",
  "labelGradientRotation": "Angle (Degrees)",
  "labelUploadLogo": "Upload Custom Image",
  "labelPresetLogo": "Preset Brand Logo",
  "logoPresetNone": "No Logo",
  "labelLogoSize": "Logo Scale",
  "labelLogoMargin": "Logo Padding Margin",
  "labelClearDots": "Erase dots behind logo (Recommended)",
  "downloadBtnPng": "Download PNG",
  "downloadBtnSvg": "Download SVG",
  "downloadBtnJpg": "Download JPEG",
  "resetBtn": "Reset Generator",
  "statusInit": "Enter details to generate your customized QR code...",
  "statusDone": "Your custom QR code is ready!",
  "statusError": "Could not compile QR code config. Please check your data.",
  "features": [
    {
      "title": "Stunning Customization",
      "text": "Change patterns, frames, and background styles with multi-color gradients and custom brand icons."
    },
    {
      "title": "100% Local & Safe",
      "text": "Your QR inputs and custom logos are processed inside your browser memory. We never upload your assets."
    },
    {
      "title": "Print-Ready Vector SVG",
      "text": "Download high-resolution PNG, JPEG, or scalable vector SVG files perfect for high-quality printing."
    }
  ],
  "footerCredit": "Part of oLoveTools suite",
  "seoHeroTitle": "Create Beautiful, Brand-Aligned QR Codes in Seconds",
  "seoHeroText": "Generic black-and-white QR codes are easily ignored. QR-Bolt lets you match your QR designs with your company branding, logos, and custom color schemes. Since all processing runs locally on your device, your private network configurations or confidential URLs are kept completely safe.",
  "seoHeroList": [
    "No registration or limits",
    "Generates offline-compatible QR codes",
    "Completely free without trial restrictions"
  ],
  "seoBrowserSpeedTitle": "Fast Client-Side Generation",
  "seoBrowserSpeedText": "Using high-performance browser rendering engines, QR-Bolt renders designs immediately inside a virtual canvas. Export options are coded to output raw vectors or high-density pixels instantly.",
  "seoSecondaryTitle": "Free customized QR creator on your device",
  "seoKeywordsTitle": "Keywords",
  "seoKeywords": [
    "Custom QR generator",
    "QR code with logo",
    "WiFi QR code generator",
    "Free QR code online",
    "Vector QR code creator",
    "SVG QR code generator",
    "E-mail QR code",
    "Gradient QR code maker"
  ],
  "seoUseCaseTitle": "Perfect for Menus, Flyer Designs & Product Packaging",
  "seoUseCaseText": "Place your custom QR codes on physical packaging, restaurant table cards, business cards, or event posters. Styled codes drastically increase scan conversion rates.",
  "seoPrivacyTitle": "Uncompromising Data Security",
  "seoPrivacyText": "Many online QR generators track your link scans and capture your personal details. QR-Bolt runs entirely client-side. The compiled QR holds static data, and the logo image is embedded locally, assuring total security.",
  "faqTitle": "Frequently Asked Questions",
  "faq": [
    {
      "question": "Are these QR codes static or dynamic?",
      "answer": "All QR codes generated by QR-Bolt are static. This means they contain the raw data directly and will never expire, require subscription fees, or redirect through external ad servers."
    },
    {
      "question": "Can I add any logo format?",
      "answer": "Yes. You can upload standard image formats including PNG, JPEG, and WebP, or pick from our brand presets (WhatsApp, Instagram, YouTube, X, GitHub, LinkedIn)."
    },
    {
      "question": "How do I make sure my QR code is scan-ready?",
      "answer": "Ensure there is high contrast between the pattern colors and the background color (dark patterns on light backgrounds scan best). Keep the logo size below 25% scale to prevent coverage of critical error-correction modules."
    },
    {
      "question": "How does the WiFi QR code work?",
      "answer": "When scanned by iOS or Android camera apps, WiFi QRs automatically prompt the device to connect to your network SSID using the provided credentials, without typing them manually."
    }
  ],
  "footerTagline": "Free styled QR Code generator running 100% locally on your device.",
  "privacyPolicy": "Privacy Policy",
  "termsOfService": "Terms of Service",
  "cookiePolicy": "Cookie Policy",
  "contactForIdeas": "Contact for ideas and feedback:",
  "emailCopied": "Email copied to clipboard!",
  "emailAddress": "adrian.contact.me.69@gmail.com",
  "privacyContent": "Your privacy is important to us.\n\nAll QR generation functions are performed locally in your web browser. No URL data, passwords, emails, or logo images are ever sent to our servers. We do not track scan activity.\n\nYour QR codes are generated entirely in client memory.",
  "termsContent": "By using QR-Bolt, you agree to these terms.\n\n1. This tool is provided \"as-is\" without any warranties.\n2. We are not responsible for any scan failures, data errors, or business disruptions arising from using this tool.\n3. You are responsible for the legal validity of the content encoded.\n4. We reserve the right to modify these terms at any time.",
  "cookiesContent": "We use cookies to improve your experience.\n\n1. Essential Cookies: Required for site operations.\n2. Preference Cookies: Used to save your language and cookie preferences.\n\nYou can configure cookies in your browser settings.",
  "contact": "Contact"
};
