export default {
  "title": "UUID-Generator",
  "seo_title": "UUID-Generator | Free Online UUID v4 & v5 Generator",
  "seo_description": "Generate random UUIDs (v4) and named UUIDs (v5) in bulk up to 500 at once 100% locally in your browser using Web Crypto API. Free online UUID generator.",
  "seoHeroTitle": "UUID v4 & v5 Bulk Generator",
  "seoHeroText": "Instantly generate up to 500 random UUIDs (version 4) or named UUIDs (version 5 with namespace) using the browser's native Web Crypto API. All generation happens locally — no server calls, no tracking.",
  "label_version": "UUID Version",
  "option_v4": "v4 (Random)",
  "option_v5": "v5 (Named + SHA-1)",
  "label_count": "Count",
  "label_namespace": "Namespace UUID",
  "label_name": "Name",
  "label_uuids_generated": "UUIDs Generated",
  "label_no_uuids": "No UUIDs generated yet. Adjust the settings above.",
  "error_invalid_namespace": "Invalid namespace UUID format. Use standard UUID format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "error_fix_namespace": "Please fix the namespace UUID to generate v5 UUIDs.",
  "button_regenerate": "Regenerate",
  "button_copied_all": "Copied All!",
  "button_download": "Download .txt",
  "button_reset": "Reset",
  "tooltip_copy": "Copy to clipboard",
  "seoBrowserSpeedTitle": "Web Crypto API Powered",
  "seoBrowserSpeedText": "UUIDs are generated using the browser's native crypto.randomUUID() for v4 and crypto.subtle.digest('SHA-1') for v5, ensuring cryptographic quality at hardware speed with zero server processing.",
  "seoUseCaseTitle": "Batch Generation",
  "seoUseCaseText": "Generate up to 500 UUIDs in a single click. Perfect for database seeding, test data generation, unique session IDs, or any scenario requiring multiple unique identifiers at once.",
  "seoPrivacyTitle": "100% Private & Secure",
  "seoPrivacyText": "No databases, tracking, or network uploads. All UUID generation happens entirely in your browser's crypto subsystem. Your data never leaves your device.",
  "seoKeywords": ["uuid generator", "uuid v4", "uuid v5", "guid generator", "random uuid", "bulk uuid", "unique identifier"],
  "faqTitle": "Frequently Asked Questions",
  "faq": [
    {
      "question": "What is the difference between UUID v4 and v5?",
      "answer": "UUID v4 is generated using random numbers, making each UUID unique and unpredictable. UUID v5 is generated by hashing a namespace UUID and a name string using SHA-1, meaning the same namespace+name always produces the same UUID."
    },
    {
      "question": "Can I generate multiple UUIDs at once?",
      "answer": "Yes. Use the count slider to generate anywhere from 1 to 500 UUIDs in a single batch. All UUIDs are generated instantly and can be copied individually or all at once."
    },
    {
      "question": "Are these UUIDs cryptographically secure?",
      "answer": "Yes. Version 4 UUIDs use the browser's native crypto.randomUUID() function which provides cryptographic randomness. Version 5 UUIDs use the Web Crypto API's SHA-1 digest function."
    }
  ],
  "footerTagline": "Fast, secure UUID v4 and v5 bulk generator powered by Web Crypto API — 100% local in your browser.",
  "footerCredit": "Part of the oLoveTools suite",
  "emailAddress": "adrian.contact.me.69@gmail.com",
  "emailCopied": "Copied!",
  "contactForIdeas": "Contact for ideas and comments:"
};
