// ============================================================================
// Tool Visual Themes
// Each tool has a unique "world" — color, mood, shape, motion personality.
// This registry is the single source of truth for tool chrome styling.
// ============================================================================

export type ToolTheme = {
  slug: string;
  name: string;
  world: string;
  emoji: string;
  primary: string;
  primaryHex: string;
  bg: string;
  surface: string;
  text: string;
  textMuted: string;
  border: string;
  radius: 'sm' | 'md' | 'lg' | 'xl' | '2xl' | '3xl' | 'full';
  font: 'sans' | 'mono' | 'outfit' | 'jakarta';
  motion: 'subtle' | 'normal' | 'energetic';
  grain: 'none' | 'soft' | 'strong';
};

const RADIUS_MAP: Record<ToolTheme['radius'], string> = {
  sm: 'rounded-md',
  md: 'rounded-xl',
  lg: 'rounded-2xl',
  xl: 'rounded-3xl',
  '2xl': 'rounded-[2rem]',
  '3xl': 'rounded-[2.5rem]',
  full: 'rounded-full',
};

const FONT_MAP: Record<ToolTheme['font'], string> = {
  sans: 'font-sans',
  mono: 'font-mono',
  outfit: 'font-outfit',
  jakarta: 'font-jakarta',
};

export function radiusClass(t: ToolTheme): string {
  return RADIUS_MAP[t.radius];
}

export function fontClass(t: ToolTheme): string {
  return FONT_MAP[t.font];
}

// ============================================================================
// Themes registry — all 55 tools
// ============================================================================

export const themes: Record<string, ToolTheme> = {
  // ===========================================================================
  // ORIGINAL TOOLS (1-5) — kept for consistency with existing visuals
  // ===========================================================================
  clipy: {
    slug: 'clipy',
    name: 'Clipy',
    world: 'Stream',
    emoji: '🎬',
    primary: 'indigo-400',
    primaryHex: '#9146ff',
    bg: '#050507',
    surface: 'rgba(24, 24, 27, 0.6)',
    text: '#efeff1',
    textMuted: '#a1a1aa',
    border: 'rgba(145, 70, 255, 0.3)',
    radius: 'xl',
    font: 'sans',
    motion: 'energetic',
    grain: 'strong',
  },
  twitchbolt: {
    slug: 'twitchbolt',
    name: 'TwitchBolt',
    world: 'Stream',
    emoji: '⚡',
    primary: 'purple-500',
    primaryHex: '#7c3aed',
    bg: '#070708',
    surface: 'rgba(24, 24, 27, 0.6)',
    text: '#efeff1',
    textMuted: '#a1a1aa',
    border: 'rgba(124, 58, 237, 0.3)',
    radius: 'xl',
    font: 'outfit',
    motion: 'energetic',
    grain: 'soft',
  },
  kickbolt: {
    slug: 'kickbolt',
    name: 'KickBolt',
    world: 'Stream',
    emoji: '⚡',
    primary: 'green-400',
    primaryHex: '#53fc18',
    bg: '#070708',
    surface: 'rgba(20, 26, 20, 0.6)',
    text: '#efeff1',
    textMuted: '#a1a1aa',
    border: 'rgba(83, 252, 24, 0.3)',
    radius: 'xl',
    font: 'outfit',
    motion: 'energetic',
    grain: 'soft',
  },
  formatflow: {
    slug: 'formatflow',
    name: 'FormatFlow',
    world: 'Code',
    emoji: '⌨️',
    primary: 'sky-400',
    primaryHex: '#38bdf8',
    bg: '#080c14',
    surface: 'rgba(17, 24, 39, 0.4)',
    text: '#e2e8f0',
    textMuted: '#94a3b8',
    border: 'rgba(56, 189, 248, 0.3)',
    radius: 'lg',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  pastesnap: {
    slug: 'pastesnap',
    name: 'PasteSnap',
    world: 'Paste',
    emoji: '📋',
    primary: 'indigo-400',
    primaryHex: '#6366f1',
    bg: '#04050a',
    surface: 'rgba(255, 255, 255, 0.03)',
    text: '#f3f4f6',
    textMuted: '#9ca3af',
    border: 'rgba(99, 102, 241, 0.3)',
    radius: '2xl',
    font: 'jakarta',
    motion: 'normal',
    grain: 'soft',
  },

  // ===========================================================================
  // TOOLS 6-55 — the redesign batch
  // Each has a distinct visual world, not just a color swap
  // ===========================================================================
  compresssnap: {
    slug: 'compresssnap',
    name: 'CompressSnap',
    world: 'Lab',
    emoji: '🗜️',
    primary: 'cyan-400',
    primaryHex: '#06b6d4',
    bg: '#05090e',
    surface: 'rgba(8, 13, 22, 0.4)',
    text: '#f0f9ff',
    textMuted: '#64748b',
    border: 'rgba(6, 182, 212, 0.25)',
    radius: 'xl',
    font: 'jakarta',
    motion: 'subtle',
    grain: 'soft',
  },
  backgroundremover: {
    slug: 'backgroundremover',
    name: 'Background Remover',
    world: 'Magic',
    emoji: '✨',
    primary: 'pink-400',
    primaryHex: '#ec4899',
    bg: '#08060b',
    surface: 'rgba(15, 10, 25, 0.4)',
    text: '#fdf2f8',
    textMuted: '#9ca3af',
    border: 'rgba(236, 72, 153, 0.25)',
    radius: 'full',
    font: 'outfit',
    motion: 'energetic',
    grain: 'none',
  },
  'pdf-flow': {
    slug: 'pdf-flow',
    name: 'PDFFlow',
    world: 'Document',
    emoji: '📄',
    primary: 'red-500',
    primaryHex: '#ef4444',
    bg: '#0c0506',
    surface: 'rgba(20, 10, 12, 0.4)',
    text: '#fef2f2',
    textMuted: '#9ca3af',
    border: 'rgba(239, 68, 68, 0.25)',
    radius: 'md',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  recordsnap: {
    slug: 'recordsnap',
    name: 'RecordSnap',
    world: 'Broadcast',
    emoji: '⏺️',
    primary: 'amber-400',
    primaryHex: '#f59e0b',
    bg: '#0b0805',
    surface: 'rgba(20, 15, 10, 0.4)',
    text: '#fffbeb',
    textMuted: '#9ca3af',
    border: 'rgba(245, 158, 11, 0.25)',
    radius: 'lg',
    font: 'sans',
    motion: 'energetic',
    grain: 'soft',
  },
  'qr-bolt': {
    slug: 'qr-bolt',
    name: 'QRBolt',
    world: 'Scan',
    emoji: '⬛',
    primary: 'emerald-400',
    primaryHex: '#10b981',
    bg: '#050907',
    surface: 'rgba(10, 20, 15, 0.4)',
    text: '#ecfdf5',
    textMuted: '#9ca3af',
    border: 'rgba(16, 185, 129, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  codecard: {
    slug: 'codecard',
    name: 'CodeCard',
    world: 'Terminal',
    emoji: '💻',
    primary: 'indigo-400',
    primaryHex: '#6366f1',
    bg: '#06050a',
    surface: 'rgba(10, 8, 18, 0.4)',
    text: '#eef2ff',
    textMuted: '#9ca3af',
    border: 'rgba(99, 102, 241, 0.25)',
    radius: 'lg',
    font: 'mono',
    motion: 'subtle',
    grain: 'none',
  },
  cropsnap: {
    slug: 'cropsnap',
    name: 'CropSnap',
    world: 'Surgical',
    emoji: '✂️',
    primary: 'rose-500',
    primaryHex: '#f43f5e',
    bg: '#090506',
    surface: 'rgba(20, 10, 12, 0.4)',
    text: '#fff1f2',
    textMuted: '#9ca3af',
    border: 'rgba(244, 63, 94, 0.25)',
    radius: 'sm',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'css-designer': {
    slug: 'css-designer',
    name: 'CSS Designer',
    world: 'Atelier',
    emoji: '🎨',
    primary: 'violet-400',
    primaryHex: '#8b5cf6',
    bg: '#07060b',
    surface: 'rgba(15, 10, 25, 0.4)',
    text: '#f5f3ff',
    textMuted: '#9ca3af',
    border: 'rgba(139, 92, 246, 0.25)',
    radius: 'full',
    font: 'outfit',
    motion: 'normal',
    grain: 'soft',
  },
  'json-flow': {
    slug: 'json-flow',
    name: 'JSONFlow',
    world: 'Blueprint',
    emoji: '🗂️',
    primary: 'emerald-400',
    primaryHex: '#10b981',
    bg: '#050807',
    surface: 'rgba(10, 15, 12, 0.4)',
    text: '#ecfdf5',
    textMuted: '#9ca3af',
    border: 'rgba(16, 185, 129, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  socialbolt: {
    slug: 'socialbolt',
    name: 'SocialBolt',
    world: 'Network',
    emoji: '🌐',
    primary: 'indigo-400',
    primaryHex: '#6366f1',
    bg: '#050508',
    surface: 'rgba(10, 10, 15, 0.4)',
    text: '#eef2ff',
    textMuted: '#9ca3af',
    border: 'rgba(99, 102, 241, 0.25)',
    radius: 'full',
    font: 'sans',
    motion: 'energetic',
    grain: 'soft',
  },
  'tts-bolt': {
    slug: 'tts-bolt',
    name: 'TTSBolt',
    world: 'Voice',
    emoji: '🔊',
    primary: 'amber-400',
    primaryHex: '#f59e0b',
    bg: '#060504',
    surface: 'rgba(20, 12, 10, 0.4)',
    text: '#fffbeb',
    textMuted: '#9ca3af',
    border: 'rgba(245, 158, 11, 0.25)',
    radius: 'full',
    font: 'sans',
    motion: 'energetic',
    grain: 'soft',
  },
  'gif-bolt': {
    slug: 'gif-bolt',
    name: 'GIFBolt',
    world: 'Animation',
    emoji: '🎞️',
    primary: 'fuchsia-400',
    primaryHex: '#d946ef',
    bg: '#060406',
    surface: 'rgba(20, 10, 20, 0.4)',
    text: '#fdf4ff',
    textMuted: '#9ca3af',
    border: 'rgba(217, 70, 239, 0.25)',
    radius: 'xl',
    font: 'outfit',
    motion: 'energetic',
    grain: 'soft',
  },
  audiosnap: {
    slug: 'audiosnap',
    name: 'AudioSnap',
    world: 'Wave',
    emoji: '🎙️',
    primary: 'rose-400',
    primaryHex: '#f43f5e',
    bg: '#060405',
    surface: 'rgba(20, 10, 15, 0.4)',
    text: '#fff1f2',
    textMuted: '#9ca3af',
    border: 'rgba(244, 63, 94, 0.25)',
    radius: 'lg',
    font: 'sans',
    motion: 'energetic',
    grain: 'soft',
  },
  drawsnap: {
    slug: 'drawsnap',
    name: 'DrawSnap',
    world: 'Canvas',
    emoji: '🖌️',
    primary: 'purple-400',
    primaryHex: '#a855f7',
    bg: '#08060a',
    surface: 'rgba(22, 12, 30, 0.4)',
    text: '#faf5ff',
    textMuted: '#9ca3af',
    border: 'rgba(168, 85, 247, 0.25)',
    radius: 'lg',
    font: 'outfit',
    motion: 'normal',
    grain: 'soft',
  },
  diffsnap: {
    slug: 'diffsnap',
    name: 'DiffSnap',
    world: 'Compare',
    emoji: '🔀',
    primary: 'cyan-400',
    primaryHex: '#06b6d4',
    bg: '#050809',
    surface: 'rgba(10, 20, 22, 0.4)',
    text: '#ecfeff',
    textMuted: '#9ca3af',
    border: 'rgba(6, 182, 212, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'watermark-snap': {
    slug: 'watermark-snap',
    name: 'WatermarkSnap',
    world: 'Stamp',
    emoji: '🖋️',
    primary: 'amber-500',
    primaryHex: '#f59e0b',
    bg: '#080604',
    surface: 'rgba(22, 15, 10, 0.4)',
    text: '#fef3c7',
    textMuted: '#9ca3af',
    border: 'rgba(245, 158, 11, 0.25)',
    radius: 'sm',
    font: 'outfit',
    motion: 'subtle',
    grain: 'soft',
  },
  'favicon-bolt': {
    slug: 'favicon-bolt',
    name: 'FaviconBolt',
    world: 'Pixel',
    emoji: '🔲',
    primary: 'blue-500',
    primaryHex: '#3b82f6',
    bg: '#030712',
    surface: 'rgba(15, 23, 42, 0.4)',
    text: '#eff6ff',
    textMuted: '#9ca3af',
    border: 'rgba(59, 130, 246, 0.25)',
    radius: 'sm',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'exif-clear': {
    slug: 'exif-clear',
    name: 'EXIF Cleaner',
    world: 'Privacy',
    emoji: '🛡️',
    primary: 'emerald-500',
    primaryHex: '#10b981',
    bg: '#020617',
    surface: 'rgba(2, 6, 23, 0.4)',
    text: '#ecfdf5',
    textMuted: '#9ca3af',
    border: 'rgba(16, 185, 129, 0.25)',
    radius: 'md',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'meme-bolt': {
    slug: 'meme-bolt',
    name: 'MemeBolt',
    world: 'Fun',
    emoji: '😂',
    primary: 'fuchsia-500',
    primaryHex: '#d946ef',
    bg: '#020205',
    surface: 'rgba(15, 2, 20, 0.4)',
    text: '#fdf4ff',
    textMuted: '#9ca3af',
    border: 'rgba(217, 70, 239, 0.25)',
    radius: 'full',
    font: 'outfit',
    motion: 'energetic',
    grain: 'soft',
  },
  wordflow: {
    slug: 'wordflow',
    name: 'WordFlow',
    world: 'Text',
    emoji: '📝',
    primary: 'teal-400',
    primaryHex: '#14b8a6',
    bg: '#030708',
    surface: 'rgba(10, 20, 18, 0.4)',
    text: '#f0fdfa',
    textMuted: '#9ca3af',
    border: 'rgba(20, 184, 166, 0.25)',
    radius: 'lg',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'markdown-live': {
    slug: 'markdown-live',
    name: 'MarkdownLive',
    world: 'Markdown',
    emoji: '📑',
    primary: 'violet-500',
    primaryHex: '#8b5cf6',
    bg: '#030208',
    surface: 'rgba(10, 5, 20, 0.4)',
    text: '#f5f3ff',
    textMuted: '#9ca3af',
    border: 'rgba(139, 92, 246, 0.25)',
    radius: 'md',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'hash-bolt': {
    slug: 'hash-bolt',
    name: 'HashBolt',
    world: 'Hash',
    emoji: '#️⃣',
    primary: 'sky-400',
    primaryHex: '#0ea5e9',
    bg: '#020813',
    surface: 'rgba(2, 8, 20, 0.4)',
    text: '#f0f9ff',
    textMuted: '#9ca3af',
    border: 'rgba(14, 165, 233, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'zip-flow': {
    slug: 'zip-flow',
    name: 'ZipFlow',
    world: 'Archive',
    emoji: '🗜️',
    primary: 'amber-500',
    primaryHex: '#f59e0b',
    bg: '#0c0802',
    surface: 'rgba(20, 12, 2, 0.4)',
    text: '#fef3c7',
    textMuted: '#9ca3af',
    border: 'rgba(245, 158, 11, 0.25)',
    radius: 'lg',
    font: 'sans',
    motion: 'normal',
    grain: 'soft',
  },
  'regex-flow': {
    slug: 'regex-flow',
    name: 'RegexFlow',
    world: 'Pattern',
    emoji: '🔣',
    primary: 'fuchsia-500',
    primaryHex: '#d946ef',
    bg: '#08040a',
    surface: 'rgba(22, 10, 20, 0.4)',
    text: '#fdf4ff',
    textMuted: '#9ca3af',
    border: 'rgba(217, 70, 239, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'lottie-viewer': {
    slug: 'lottie-viewer',
    name: 'Lottie Viewer',
    world: 'Lottie',
    emoji: '🎭',
    primary: 'indigo-500',
    primaryHex: '#6366f1',
    bg: '#05050a',
    surface: 'rgba(15, 12, 25, 0.4)',
    text: '#eef2ff',
    textMuted: '#9ca3af',
    border: 'rgba(99, 102, 241, 0.25)',
    radius: 'xl',
    font: 'outfit',
    motion: 'energetic',
    grain: 'soft',
  },
  'svg-optimizer': {
    slug: 'svg-optimizer',
    name: 'SVG Optimizer',
    world: 'SVG',
    emoji: '🎯',
    primary: 'cyan-500',
    primaryHex: '#06b6d4',
    bg: '#04080a',
    surface: 'rgba(3, 15, 20, 0.4)',
    text: '#ecfeff',
    textMuted: '#9ca3af',
    border: 'rgba(6, 182, 212, 0.25)',
    radius: 'sm',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'graph-flow': {
    slug: 'graph-flow',
    name: 'GraphFlow',
    world: 'Graph',
    emoji: '📊',
    primary: 'amber-500',
    primaryHex: '#f59e0b',
    bg: '#0a0804',
    surface: 'rgba(20, 12, 3, 0.4)',
    text: '#fef3c7',
    textMuted: '#9ca3af',
    border: 'rgba(245, 158, 11, 0.25)',
    radius: 'lg',
    font: 'sans',
    motion: 'normal',
    grain: 'soft',
  },
  'url-bolt': {
    slug: 'url-bolt',
    name: 'URLBolt',
    world: 'URL',
    emoji: '🔗',
    primary: 'emerald-500',
    primaryHex: '#10b981',
    bg: '#020a08',
    surface: 'rgba(4, 19, 14, 0.4)',
    text: '#ecfdf5',
    textMuted: '#9ca3af',
    border: 'rgba(16, 185, 129, 0.25)',
    radius: 'md',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'base64-bolt': {
    slug: 'base64-bolt',
    name: 'Base64Bolt',
    world: 'Encode',
    emoji: '🔐',
    primary: 'blue-500',
    primaryHex: '#3b82f6',
    bg: '#020610',
    surface: 'rgba(15, 23, 42, 0.4)',
    text: '#eff6ff',
    textMuted: '#9ca3af',
    border: 'rgba(59, 130, 246, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'uuid-generator': {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    world: 'ID',
    emoji: '🆔',
    primary: 'blue-400',
    primaryHex: '#3b82f6',
    bg: '#030712',
    surface: 'rgba(15, 23, 42, 0.4)',
    text: '#eff6ff',
    textMuted: '#9ca3af',
    border: 'rgba(59, 130, 246, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'list-mixer': {
    slug: 'list-mixer',
    name: 'List Mixer',
    world: 'List',
    emoji: '🧮',
    primary: 'blue-500',
    primaryHex: '#3b82f6',
    bg: '#020610',
    surface: 'rgba(15, 23, 42, 0.4)',
    text: '#eff6ff',
    textMuted: '#9ca3af',
    border: 'rgba(59, 130, 246, 0.25)',
    radius: 'md',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'html-sanitizer': {
    slug: 'html-sanitizer',
    name: 'HTML Sanitizer',
    world: 'Sanitize',
    emoji: '🧼',
    primary: 'emerald-500',
    primaryHex: '#10b981',
    bg: '#020617',
    surface: 'rgba(2, 6, 23, 0.4)',
    text: '#ecfdf5',
    textMuted: '#9ca3af',
    border: 'rgba(16, 185, 129, 0.25)',
    radius: 'md',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  colorsnap: {
    slug: 'colorsnap',
    name: 'ColorSnap',
    world: 'Color',
    emoji: '🎨',
    primary: 'pink-400',
    primaryHex: '#ec4899',
    bg: '#08060b',
    surface: 'rgba(15, 10, 25, 0.4)',
    text: '#fdf2f8',
    textMuted: '#9ca3af',
    border: 'rgba(236, 72, 153, 0.25)',
    radius: 'full',
    font: 'outfit',
    motion: 'normal',
    grain: 'none',
  },
  'hex-to-rgb': {
    slug: 'hex-to-rgb',
    name: 'Hex to RGB',
    world: 'Color',
    emoji: '🌈',
    primary: 'pink-500',
    primaryHex: '#ec4899',
    bg: '#08060b',
    surface: 'rgba(15, 10, 25, 0.4)',
    text: '#fdf2f8',
    textMuted: '#9ca3af',
    border: 'rgba(236, 72, 153, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'none',
  },
  'aspect-ratio': {
    slug: 'aspect-ratio',
    name: 'Aspect Ratio',
    world: 'Ratio',
    emoji: '🟦',
    primary: 'lime-400',
    primaryHex: '#84cc16',
    bg: '#080a02',
    surface: 'rgba(15, 18, 10, 0.4)',
    text: '#f7fee7',
    textMuted: '#9ca3af',
    border: 'rgba(132, 204, 22, 0.25)',
    radius: 'sm',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  unitflow: {
    slug: 'unitflow',
    name: 'UnitFlow',
    world: 'Unit',
    emoji: '📏',
    primary: 'teal-500',
    primaryHex: '#14b8a6',
    bg: '#020a08',
    surface: 'rgba(4, 19, 16, 0.4)',
    text: '#f0fdfa',
    textMuted: '#9ca3af',
    border: 'rgba(20, 184, 166, 0.25)',
    radius: 'md',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'sql-flow': {
    slug: 'sql-flow',
    name: 'SQLFlow',
    world: 'SQL',
    emoji: '🗃️',
    primary: 'emerald-500',
    primaryHex: '#10b981',
    bg: '#020a08',
    surface: 'rgba(4, 19, 14, 0.4)',
    text: '#ecfdf5',
    textMuted: '#9ca3af',
    border: 'rgba(16, 185, 129, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'cron-flow': {
    slug: 'cron-flow',
    name: 'CronFlow',
    world: 'Cron',
    emoji: '⏰',
    primary: 'sky-500',
    primaryHex: '#0ea5e9',
    bg: '#020813',
    surface: 'rgba(2, 8, 19, 0.4)',
    text: '#f0f9ff',
    textMuted: '#9ca3af',
    border: 'rgba(14, 165, 233, 0.25)',
    radius: 'md',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'xml-json': {
    slug: 'xml-json',
    name: 'XML to JSON',
    world: 'Data',
    emoji: '🔄',
    primary: 'amber-500',
    primaryHex: '#f59e0b',
    bg: '#0c0802',
    surface: 'rgba(20, 12, 2, 0.4)',
    text: '#fef3c7',
    textMuted: '#9ca3af',
    border: 'rgba(245, 158, 11, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'binary-flow': {
    slug: 'binary-flow',
    name: 'BinaryFlow',
    world: 'Binary',
    emoji: '💾',
    primary: 'amber-500',
    primaryHex: '#f59e0b',
    bg: '#0c0802',
    surface: 'rgba(20, 12, 2, 0.4)',
    text: '#fef3c7',
    textMuted: '#9ca3af',
    border: 'rgba(245, 158, 11, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'morse-flow': {
    slug: 'morse-flow',
    name: 'MorseFlow',
    world: 'Morse',
    emoji: '📡',
    primary: 'fuchsia-500',
    primaryHex: '#d946ef',
    bg: '#08040a',
    surface: 'rgba(22, 10, 20, 0.4)',
    text: '#fdf4ff',
    textMuted: '#9ca3af',
    border: 'rgba(217, 70, 239, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'normal',
    grain: 'soft',
  },
  'epoch-flow': {
    slug: 'epoch-flow',
    name: 'EpochFlow',
    world: 'Time',
    emoji: '⏳',
    primary: 'indigo-500',
    primaryHex: '#6366f1',
    bg: '#05050a',
    surface: 'rgba(15, 12, 25, 0.4)',
    text: '#eef2ff',
    textMuted: '#9ca3af',
    border: 'rgba(99, 102, 241, 0.25)',
    radius: 'md',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'time-bolt': {
    slug: 'time-bolt',
    name: 'TimeBolt',
    world: 'Time',
    emoji: '⏱️',
    primary: 'sky-500',
    primaryHex: '#0ea5e9',
    bg: '#020813',
    surface: 'rgba(2, 8, 19, 0.4)',
    text: '#f0f9ff',
    textMuted: '#9ca3af',
    border: 'rgba(14, 165, 233, 0.25)',
    radius: 'sm',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'device-test': {
    slug: 'device-test',
    name: 'Device Test',
    world: 'Device',
    emoji: '📱',
    primary: 'blue-500',
    primaryHex: '#3b82f6',
    bg: '#030712',
    surface: 'rgba(15, 23, 42, 0.4)',
    text: '#eff6ff',
    textMuted: '#9ca3af',
    border: 'rgba(59, 130, 246, 0.25)',
    radius: 'lg',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'lorem-flow': {
    slug: 'lorem-flow',
    name: 'LoremFlow',
    world: 'Text',
    emoji: '📜',
    primary: 'amber-500',
    primaryHex: '#f59e0b',
    bg: '#0c0802',
    surface: 'rgba(20, 12, 2, 0.4)',
    text: '#fef3c7',
    textMuted: '#9ca3af',
    border: 'rgba(245, 158, 11, 0.25)',
    radius: 'md',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  'key-doctor': {
    slug: 'key-doctor',
    name: 'Key Doctor',
    world: 'Key',
    emoji: '🔑',
    primary: 'amber-500',
    primaryHex: '#f59e0b',
    bg: '#0c0802',
    surface: 'rgba(20, 12, 2, 0.4)',
    text: '#fef3c7',
    textMuted: '#9ca3af',
    border: 'rgba(245, 158, 11, 0.25)',
    radius: 'md',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'whiteboard-flow': {
    slug: 'whiteboard-flow',
    name: 'WhiteboardFlow',
    world: 'Board',
    emoji: '📋',
    primary: 'cyan-500',
    primaryHex: '#06b6d4',
    bg: '#04080a',
    surface: 'rgba(3, 15, 20, 0.4)',
    text: '#ecfeff',
    textMuted: '#9ca3af',
    border: 'rgba(6, 182, 212, 0.25)',
    radius: 'md',
    font: 'sans',
    motion: 'normal',
    grain: 'soft',
  },
  'subtitles-bolt': {
    slug: 'subtitles-bolt',
    name: 'SubtitlesBolt',
    world: 'Subtitles',
    emoji: '💬',
    primary: 'blue-500',
    primaryHex: '#3b82f6',
    bg: '#020610',
    surface: 'rgba(4, 10, 30, 0.4)',
    text: '#eff6ff',
    textMuted: '#9ca3af',
    border: 'rgba(59, 130, 246, 0.25)',
    radius: 'md',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
  entropybolt: {
    slug: 'entropy-bolt',
    name: 'EntropyBolt',
    world: 'Password',
    emoji: '🔒',
    primary: 'emerald-500',
    primaryHex: '#10b981',
    bg: '#020a08',
    surface: 'rgba(4, 19, 14, 0.4)',
    text: '#ecfdf5',
    textMuted: '#9ca3af',
    border: 'rgba(16, 185, 129, 0.25)',
    radius: 'md',
    font: 'mono',
    motion: 'subtle',
    grain: 'soft',
  },
  'whois-bolt': {
    slug: 'whois-bolt',
    name: 'WhoisBolt',
    world: 'Whois',
    emoji: '🌍',
    primary: 'indigo-500',
    primaryHex: '#6366f1',
    bg: '#05050a',
    surface: 'rgba(15, 12, 25, 0.4)',
    text: '#eef2ff',
    textMuted: '#9ca3af',
    border: 'rgba(99, 102, 241, 0.25)',
    radius: 'md',
    font: 'sans',
    motion: 'subtle',
    grain: 'soft',
  },
};

// ============================================================================
// Helpers
// ============================================================================

export function getTheme(slug: string): ToolTheme {
  return themes[slug] ?? themes.compresssnap;
}

export const DEFAULT_THEME = themes.compresssnap;
