export interface PresetSvg {
  nameKey: string;
  fileName: string;
  code: string;
}

export const PRESET_SVGS: Record<string, PresetSvg> = {
  icon: {
    nameKey: "preset_icon",
    fileName: "app-logo-icon.svg",
    code: `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by Adobe Illustrator 27.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="512px" height="512px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
<style type="text/css">
	.st0{fill:url(#grad1);}
	.st1{fill:#FFFFFF;opacity:0.2;}
	.st2{fill:none;stroke:#FFFFFF;stroke-width:12.3456789;stroke-miterlimit:10;}
</style>
<metadata>
	<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:mx="http://mindfusion.eu/measure2/">
		<rdf:Description about="" mx:version="1.0" mx:creator="Illustrator">
		</rdf:Description>
	</rdf:RDF>
</metadata>
<defs>
	<linearGradient id="grad1" x1="0%" y1="0%" x2="100%" y2="100%">
		<stop offset="0%" style="stop-color:#06b6d4;stop-opacity:1" />
		<stop offset="100%" style="stop-color:#0ea5e9;stop-opacity:1" />
	</linearGradient>
</defs>
<g id="BackgroundGroup" inkscape:groupmode="layer" inkscape:label="Background">
	<rect x="0" y="0" class="st0" width="512.0000000" height="512.0000000" rx="120.543210"/>
</g>
<g id="UnusedGroupWithNoAttrs">
	<g id="InnerUnusedGroup">
		<!-- Central Vector Nodes -->
		<path class="st2" d="M 256.0000000, 100.1234567 L 390.4567890, 350.9876543 L 121.5432109, 350.9876543 Z" />
		<circle class="st1" cx="256.0000000" cy="256.0000000" r="140.6543210" />
		<circle cx="256.0" cy="100.12" r="16.789" fill="#ffffff" id="node1" />
		<circle cx="390.46" cy="350.99" r="16.789" fill="#ffffff" id="node2" />
		<circle cx="121.54" cy="350.99" r="16.789" fill="#ffffff" id="node3" />
	</g>
</g>
</svg>`
  },
  pattern: {
    nameKey: "preset_pattern",
    fileName: "geometric-pattern.svg",
    code: `<svg xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 100 100">
  <!-- Grid pattern of hexagons and triangles -->
  <style>
    .pat-bg { fill: #0f172a; }
    .pat-grid { stroke: #1e293b; stroke-width: 0.5; fill: none; }
    .pat-accent { fill: #06b6d4; opacity: 0.15; }
    .pat-node { fill: #38bdf8; }
  </style>
  <rect width="100" height="100" class="pat-bg" />
  <g id="HexGrid">
    <polygon points="50,15.47 75,30 75,60 50,74.53 25,60 25,30" class="pat-grid" />
    <polygon points="50,15.47 75,30 75,60 50,74.53 25,60 25,30" class="pat-accent" />
    <path d="M 50,0 L 50,15.47 M 0,30 L 25,30 M 75,30 L 100,30 M 25,60 L 0,60 M 75,60 L 100,60 M 50,74.53 L 50,100" class="pat-grid" />
    <circle cx="50" cy="15.470000" r="1.500000" class="pat-node" />
    <circle cx="75" cy="30.000000" r="1.500000" class="pat-node" />
    <circle cx="75" cy="60.000000" r="1.500000" class="pat-node" />
    <circle cx="50" cy="74.530000" r="1.500000" class="pat-node" />
    <circle cx="25" cy="60.000000" r="1.500000" class="pat-node" />
    <circle cx="25" cy="30.000000" r="1.500000" class="pat-node" />
  </g>
</svg>`
  },
  graphic: {
    nameKey: "preset_graphic",
    fileName: "vector-graphic.svg",
    code: `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   width="120"
   height="120"
   viewBox="0 0 120 120"
   version="1.1"
   id="svg8"
   inkscape:version="1.0.2 (e86c870879, 2021-01-15)"
   sodipodi:docname="vector-badge.svg">
  <sodipodi:namedview
     id="base"
     pagecolor="#ffffff"
     bordercolor="#666666"
     borderopacity="1.0"
     inkscape:pageopacity="0.0"
     inkscape:pageshadow="2"
     inkscape:zoom="5.6568542"
     inkscape:cx="60"
     inkscape:cy="60"
     inkscape:document-units="px"
     inkscape:current-layer="layer1"
     showgrid="true" />
  <metadata
     id="metadata5">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1">
    <rect
       id="rect12"
       width="100.123456"
       height="100.123456"
       x="9.938271"
       y="9.938271"
       rx="15.2468"
       style="fill:#06b6d4;stroke:#0891b2;stroke-width:3.123456" />
    <path
       id="star-shape"
       d="M 60,30 L 68.81966,47.86474 L 88.53169,50.72949 L 74.26584,64.63525 L 77.63932,84.27050 L 60,75 L 42.36067,84.27050 L 45.73415,64.63525 L 31.46830,50.72949 L 51.18033,47.86474 Z"
       style="fill:#ffffff;opacity:0.9" />
  </g>
</svg>`
  }
};
