export default {
  "privacy": {
    "title": "Política de Privacidad",
    "description": "Política de privacidad detallada para oLoveTools.",
    "content": "\n      <h2>1. Introducción</h2>\n      <p>Su privacidad es importante para nosotros. Es política de oLoveTools respetar su privacidad con respecto a cualquier información que podamos recopilar de usted a través de nuestro sitio web, olovetools.com, y otros sitios que poseemos y operamos.</p>\n      <br/>\n      <h2>2. Información que recopilamos</h2>\n      <p>Solo solicitamos información personal cuando realmente la necesitamos para brindarle un servicio. La recopilamos por medios justos y legales, con su conocimiento y consentimiento. También le informamos por qué la recopilamos y cómo se utilizará.</p>\n      <p>Para la mayoría de nuestras herramientas (como Clipy, TwitchBolt, FormatFlow y PasteSnap), el procesamiento se realiza completamente en su navegador. No almacenamos sus clips, imágenes ni código en nuestros servidores.</p>\n      <br/>\n      <h2>3. Servicios de terceros y anuncios</h2>\n      <p>Nuestro sitio web utiliza Google AdSense para publicar anuncios. Google utiliza cookies para mostrar anuncios basados en las visitas anteriores de un usuario a nuestro sitio web u otros sitios web. El uso de cookies publicitarias por parte de Google le permite a él y a sus socios publicar anuncios para nuestros usuarios basados en su visita a nuestros sitios y/u otros sitios en Internet.</p>\n      <br/>\n      <h2>4. Retención de datos</h2>\n      <p>Solo retenemos la información recopilada durante el tiempo necesario para brindarle el servicio solicitado. Los datos que almacenamos los protegeremos dentro de medios comercialmente aceptables para evitar pérdidas y robos, así como el acceso, divulgación, copia, uso o modificación no autorizados.</p>\n      <br/>\n      <h2>5. Derechos del usuario</h2>\n      <p>Usted es libre de rechazar nuestra solicitud de su información personal, con el entendimiento de que es posible que no podamos brindarle algunos de los servicios que desea.</p>\n    "
  },
  "terms": {
    "title": "Términos de Servicio",
    "description": "Términos y condiciones para el uso de oLoveTools.",
    "content": "\n      <h2>1. Términos</h2>\n      <p>Al acceder al sitio web en oLoveTools, usted acepta estar sujeto a estos términos de servicio, todas las leyes y regulaciones aplicables, y acepta que es responsable del cumplimiento de las leyes locales aplicables. Si no está de acuerdo con alguno de estos términos, tiene prohibido usar o acceder a este sitio.</p>\n      <br/>\n      <h2>2. Licencia de uso</h2>\n      <p>Se otorga permiso para descargar temporalmente una copia de los materiales (información o software) en el sitio web de oLoveTools solo para visualización transitoria personal y no comercial. Esta es la concesión de una licencia, no una transferencia de título.</p>\n      <br/>\n      <h2>3. Descargo de responsabilidad</h2>\n      <p>Los materiales en el sitio web de oLoveTools se proporcionan \"tal cual\". oLoveTools no ofrece garantías, expresas o implícitas, y por la presente renuncia y niega todas las demás garantías, incluidas, entre otras, las garantías implícitas o las condiciones de comerciabilidad, idoneidad para un propósito particular o no infracción de la propiedad intelectual u otra violación de derechos.</p>\n      <br/>\n      <h2>4. Limitaciones</h2>\n      <p>En ningún caso oLoveTools o sus proveedores serán responsables de ningún daño (incluidos, entre otros, daños por pérdida de datos o ganancias, o debido a la interrupción del negocio) que surja del uso o la imposibilidad de usar los materiales en el sitio web de oLoveTools.</p>\n      <br/>\n      <h2>5. Contenido de terceros</h2>\n      <p>Algunas de nuestras herramientas (por ejemplo, Clipy, TwitchBolt) interactúan con API de terceros (como Twitch). Al utilizar estas herramientas, también debe cumplir con los Términos de Servicio respectivos de esas plataformas de terceros. No alojamos ni somos dueños del contenido multimedia recuperado a través de estas API.</p>\n    "
  },
  "cookies": {
    "title": "Política de Cookies",
    "description": "Información sobre nuestro uso de cookies y tecnologías de seguimiento.",
    "content": "\n      <h2>1. ¿Qué son las cookies?</h2>\n      <p>Las cookies son pequeños archivos de texto que se almacenan en su computadora o dispositivo móvil cuando visita un sitio web. Se utilizan ampliamente para que los sitios web funcionen, o funcionen de manera más eficiente, así como para proporcionar información a los propietarios del sitio.</p>\n      <br/>\n      <h2>2. Cómo usamos las cookies</h2>\n      <p>Utilizamos cookies para mejorar su experiencia de navegación, mostrar anuncios o contenido personalizados y analizar nuestro tráfico. Usamos cookies esenciales para recordar su preferencia de idioma y otras configuraciones.</p>\n      <br/>\n      <h2>3. Cookies de Google AdSense</h2>\n      <p>Utilizamos Google AdSense para publicar anuncios en nuestro sitio. El uso de la cookie DART por parte de Google le permite publicar anuncios para nuestros usuarios basados en su visita a nuestro sitio y otros sitios en Internet. Los usuarios pueden optar por no usar la cookie DART visitando la política de privacidad de la red de contenido y anuncios de Google.</p>\n      <br/>\n      <h2>4. Gestión de cookies</h2>\n      <p>Puede configurar su navegador para rechazar todas o algunas cookies del navegador, o para que le avise cuando los sitios web configuren o accedan a las cookies. Si deshabilita o rechaza las cookies, tenga en cuenta que algunas partes de este sitio web pueden volverse inaccesibles o no funcionar correctamente.</p>\n    "
  },
  "about": {
    "title": "Sobre oLoveTools",
    "description": "Conozca más sobre nuestra misión y las herramientas que ofrecemos.",
    "content": "\n      <h2>Nuestra Misión</h2>\n      <p>oLoveTools es un conjunto completo de utilidades en línea gratuitas y de alta calidad diseñadas para simplificar las tareas diarias de desarrolladores, diseñadores, creadores de contenido y usuarios cotidianos. Nuestra misión es proporcionar herramientas potentes que sean rápidas, seguras y accesibles directamente desde su navegador sin necesidad de instalaciones ni registros.</p>\n      <br/>\n      <h2>Nuestra Filosofía</h2>\n      <p>Creemos en la privacidad y la eficiencia. Siempre que es posible, nuestras herramientas están diseñadas para procesar datos localmente en su dispositivo. Esto significa que sus archivos, imágenes y fragmentos de código nunca salen de su computadora, lo que garantiza la máxima privacidad y un rendimiento ultrarrápido.</p>\n      <br/>\n      <h2>Las Herramientas</h2>\n      <ul>\n        <li><strong>Clipy & TwitchBolt:</strong> Descubra, organice y descargue sus clips favoritos de Twitch fácilmente.</li>\n        <li><strong>FormatFlow:</strong> Una herramienta versátil para formatear y convertir varios tipos de código y datos.</li>\n        <li><strong>PasteSnap:</strong> Capture y gestione instantáneamente las imágenes de su portapapeles con alta calidad.</li>\n      </ul>\n      <br/>\n      <p>Estamos en constante evolución y agregando nuevas funciones a nuestra plataforma. ¡Gracias por elegir oLoveTools!</p>\n    "
  },
  "nav": {
    "home": "Inicio",
    "privacy": "Privacidad",
    "terms": "Términos",
    "cookies": "Cookies",
    "about": "Nosotros"
  }
};
