export default {
  "privacy": {
    "title": "Política de Privacidade",
    "description": "Política de privacidade abrangente para oLoveTools.",
    "content": "\n      <h2>1. Introdução</h2>\n      <p>A sua privacidade é importante para nós. É política da oLoveTools respeitar a sua privacidade em relação a qualquer informação que possamos coletar de você em nosso site, olovetools.com, e outros sites que possuímos e operamos.</p>\n      <br/>\n      <h2>2. Informações que coletamos</h2>\n      <p>Solicitamos informações pessoais apenas quando realmente precisamos delas para lhe fornecer um serviço. Fazemo-lo por meios justos e legais, com o seu conhecimento e consentimento. Também informamos o motivo de estarmos coletando e como elas serão usadas.</p>\n      <p>Para a maioria de nossas ferramentas (como Clipy, TwitchBolt, FormatFlow e PasteSnap), o processamento ocorre inteiramente em seu navegador. Não armazenamos seus clipes, imagens ou códigos formatados em nossos servidores.</p>\n      <br/>\n      <h2>3. Serviços de terceiros e anúncios</h2>\n      <p>O nosso site utiliza o Google AdSense para veicular anúncios. O Google usa cookies para veicular anúncios com base em visitas anteriores de um usuário ao nosso ou a outros sites. O uso de cookies de publicidade pelo Google permite que ele e seus parceiros veiculem anúncios para nossos usuários com base em sua visita a nossos sites e/ou outros sites na Internet.</p>\n      <br/>\n      <h2>4. Retenção de dados</h2>\n      <p>Apenas retemos as informações coletadas pelo tempo necessário para fornecer o serviço solicitado. Os dados que armazenamos, os protegeremos por meios comercialmente aceitáveis ​​para evitar perdas e roubos, bem como acesso, divulgação, cópia, uso ou modificação não autorizados.</p>\n      <br/>\n      <h2>5. Direitos do usuário</h2>\n      <p>Você é livre para recusar a nossa solicitação de informações pessoais, entendendo que talvez não possamos fornecer alguns dos serviços desejados.</p>\n    "
  },
  "terms": {
    "title": "Termos de Serviço",
    "description": "Termos e condições de uso da oLoveTools.",
    "content": "\n      <h2>1. Termos</h2>\n      <p>Ao acessar o site da oLoveTools, você concorda em cumprir estes termos de serviço, todas as leis e regulamentos aplicáveis ​​e concorda que é responsável pelo cumprimento de todas as leis locais aplicáveis. Se você não concordar com algum destes termos, está proibido de usar ou acessar este site.</p>\n      <br/>\n      <h2>2. Licença de uso</h2>\n      <p>É concedida permissão para baixar temporariamente uma cópia dos materiais (informações ou software) no site da oLoveTools apenas para visualização transitória pessoal e não comercial. Esta é a concessão de uma licença, não uma transferência de título.</p>\n      <br/>\n      <h2>3. Isenção de responsabilidade</h2>\n      <p>Os materiais no site da oLoveTools são fornecidos \"como estão\". A oLoveTools não oferece garantias, expressas ou implícitas, e por meio deste isenta e nega todas as outras garantias, incluindo, sem limitação, garantias implícitas ou condições de comercialização, adequação a um propósito específico ou não violação de propriedade intelectual ou outra violação de direitos.</p>\n      <br/>\n      <h2>4. Limitações</h2>\n      <p>Em nenhum caso a oLoveTools ou seus fornecedores serão responsáveis ​​por quaisquer danos (incluindo, sem limitação, danos por perda de dados ou lucros, ou devido a interrupção de negócios) decorrentes do uso ou da incapacidade de usar os materiais no site da oLoveTools.</p>\n      <br/>\n      <h2>5. Conteúdo de Terceiros</h2>\n      <p>Algumas de nossas ferramentas (ex: Clipy, TwitchBolt) interagem com APIs de terceiros (como a Twitch). Ao usar essas ferramentas, você também deve cumprir os respectivos Termos de Serviço dessas plataformas de terceiros. Não hospedamos ou possuímos o conteúdo de mídia recuperado através dessas APIs.</p>\n    "
  },
  "cookies": {
    "title": "Política de Cookies",
    "description": "Informações sobre o nosso uso de cookies e tecnologias de rastreamento.",
    "content": "\n      <h2>1. O que são cookies?</h2>\n      <p>Os cookies são pequenos arquivos de texto que são armazenados no seu computador ou dispositivo móvel quando você visita um site. Eles são amplamente utilizados para fazer os sites funcionarem, ou funcionarem de forma mais eficiente, bem como para fornecer informações aos proprietários do site.</p>\n      <br/>\n      <h2>2. Como usamos os cookies</h2>\n      <p>Utilizamos cookies para melhorar a sua experiência de navegação, apresentar anúncios ou conteúdos personalizados e analisar o nosso tráfego. Usamos cookies essenciais para lembrar a sua preferência de idioma e outras configurações.</p>\n      <br/>\n      <h2>3. Cookies do Google AdSense</h2>\n      <p>Usamos o Google AdSense para veicular anúncios em nosso site. O uso do cookie DART pelo Google permite que ele veicule anúncios para nossos usuários com base em sua visita ao nosso site e a outros sites na Internet. Os usuários podem desativar o uso do cookie DART visitando a política de privacidade da rede de conteúdo e anúncios do Google.</p>\n      <br/>\n      <h2>4. Gerenciamento de cookies</h2>\n      <p>Você pode configurar seu navegador para recusar todos ou alguns cookies, ou para alertá-lo quando sites configurarem ou acessarem cookies. Se você desativar ou recusar cookies, observe que algumas partes deste site podem ficar inacessíveis ou não funcionar corretamente.</p>\n    "
  },
  "about": {
    "title": "Sobre a oLoveTools",
    "description": "Saiba mais sobre a nossa missão e as ferramentas que oferecemos.",
    "content": "\n      <h2>Nossa Missão</h2>\n      <p>A oLoveTools é um conjunto abrangente de utilitários online gratuitos e de alta qualidade, projetados para simplificar as tarefas diárias de desenvolvedores, designers, criadores de conteúdo e usuários comuns. Nossa missão é fornecer ferramentas poderosas que sejam rápidas, seguras e acessíveis diretamente do seu navegador, sem a necessidade de instalações ou registros.</p>\n      <br/>\n      <h2>Nossa Filosofia</h2>\n      <p>Acreditamos na privacidade e eficiência. Sempre que possível, nossas ferramentas são projetadas para processar dados localmente em seu dispositivo. Isso significa que seus arquivos, imagens e trechos de código nunca saem do seu computador, garantindo máxima privacidade e desempenho extremamente rápido.</p>\n      <br/>\n      <h2>As Ferramentas</h2>\n      <ul>\n        <li><strong>Clipy & TwitchBolt:</strong> Descubra, organize e baixe seus clipes da Twitch favoritos facilmente.</li>\n        <li><strong>FormatFlow:</strong> Uma ferramenta versátil para formatar e converter vários tipos de código e dados.</li>\n        <li><strong>PasteSnap:</strong> Capture e gerencie instantaneamente as imagens da sua área de transferência com alta qualidade.</li>\n      </ul>\n      <br/>\n      <p>Estamos constantemente evoluindo e adicionando novos recursos à nossa plataforma. Obrigado por escolher a oLoveTools!</p>\n    "
  },
  "nav": {
    "home": "Início",
    "privacy": "Privacidade",
    "terms": "Termos",
    "cookies": "Cookies",
    "about": "Sobre"
  }
};
