/**
 * Mapa slug → 3-6 herramientas relacionadas por afinidad temática (misma categoría
 * de ProjectCategory en src/constants.ts, con fallback a categorías cercanas para
 * las categorías con pocos miembros: DOCUMENT_PDF, DATA_CONVERSION, NETWORK_SYSTEM,
 * SECURITY_CRYPTO, PRODUCTIVITY). Usado por la sección SSR "Herramientas relacionadas"
 * en src/pages/[lang]/[tool]/index.astro para enlazado interno crawlable.
 */
export const RELATED_TOOLS: Record<string, string[]> = {
  'clipy': ['recordsnap', 'tts-bolt', 'audiosnap', 'subtitles-bolt', 'framesnap', 'klipy'],
  'twitchbolt': ['kickbolt', 'socialbolt', 'clip-flow'],
  'formatflow': ['unitflow', 'codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt'],
  'pastesnap': ['compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt', 'drawsnap'],
  'kickbolt': ['twitchbolt', 'socialbolt', 'clip-flow'],
  'compresssnap': ['pastesnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt', 'drawsnap'],
  'backgroundremover': ['pastesnap', 'compresssnap', 'qr-bolt', 'cropsnap', 'gif-bolt', 'drawsnap'],
  'pdf-flow': ['zip-flow', 'time-bolt', 'whiteboard-flow', 'formatflow', 'unitflow', 'pastesnap'],
  'recordsnap': ['clipy', 'tts-bolt', 'audiosnap', 'subtitles-bolt', 'framesnap', 'klipy'],
  'qr-bolt': ['pastesnap', 'compresssnap', 'backgroundremover', 'cropsnap', 'gif-bolt', 'drawsnap'],
  'codecard': ['css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow', 'graph-flow'],
  'cropsnap': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'gif-bolt', 'drawsnap'],
  'css-designer': ['codecard', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow', 'graph-flow'],
  'json-flow': ['codecard', 'css-designer', 'diffsnap', 'favicon-bolt', 'regex-flow', 'graph-flow'],
  'socialbolt': ['twitchbolt', 'kickbolt', 'clip-flow'],
  'tts-bolt': ['clipy', 'recordsnap', 'audiosnap', 'subtitles-bolt', 'framesnap', 'klipy'],
  'gif-bolt': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'drawsnap'],
  'audiosnap': ['clipy', 'recordsnap', 'tts-bolt', 'subtitles-bolt', 'framesnap', 'klipy'],
  'drawsnap': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt'],
  'diffsnap': ['codecard', 'css-designer', 'json-flow', 'favicon-bolt', 'regex-flow', 'graph-flow'],
  'watermark-snap': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt'],
  'favicon-bolt': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'regex-flow', 'graph-flow'],
  'exif-clear': ['hash-bolt', 'jwt-bolt', 'entropy-bolt', 'codecard', 'css-designer', 'json-flow', 'diffsnap'],
  'meme-bolt': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt'],
  'wordflow': ['markdown-live', 'list-mixer', 'morse-flow', 'lorem-flow'],
  'markdown-live': ['wordflow', 'list-mixer', 'morse-flow', 'lorem-flow'],
  'hash-bolt': ['jwt-bolt', 'exif-clear', 'entropy-bolt', 'codecard', 'css-designer', 'json-flow', 'diffsnap'],
  'zip-flow': ['time-bolt', 'whiteboard-flow', 'wordflow', 'markdown-live', 'list-mixer', 'morse-flow'],
  'regex-flow': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'graph-flow'],
  'lottie-viewer': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt'],
  'svg-optimizer': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt'],
  'graph-flow': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'url-bolt': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'base64-bolt': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'uuid-generator': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'list-mixer': ['wordflow', 'markdown-live', 'morse-flow', 'lorem-flow'],
  'html-sanitizer': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'colorsnap': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt'],
  'hex-to-rgb': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt'],
  'aspect-ratio': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt'],
  'unitflow': ['formatflow', 'codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt'],
  'sql-flow': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'cron-flow': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'xml-json': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'binary-flow': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'morse-flow': ['wordflow', 'markdown-live', 'list-mixer', 'lorem-flow'],
  'epoch-flow': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'time-bolt': ['zip-flow', 'whiteboard-flow', 'wordflow', 'markdown-live', 'list-mixer', 'morse-flow'],
  'device-test': ['whois-bolt', 'codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt'],
  'lorem-flow': ['wordflow', 'markdown-live', 'list-mixer', 'morse-flow'],
  'key-doctor': ['codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt', 'regex-flow'],
  'whiteboard-flow': ['zip-flow', 'time-bolt', 'wordflow', 'markdown-live', 'list-mixer', 'morse-flow'],
  'subtitles-bolt': ['clipy', 'recordsnap', 'tts-bolt', 'audiosnap', 'framesnap', 'klipy'],
  'entropy-bolt': ['exif-clear', 'hash-bolt', 'jwt-bolt', 'codecard', 'css-designer', 'json-flow', 'diffsnap'],
  'jwt-bolt': ['hash-bolt', 'entropy-bolt', 'exif-clear', 'base64-bolt', 'json-flow', 'url-bolt'],
  'whois-bolt': ['device-test', 'codecard', 'css-designer', 'json-flow', 'diffsnap', 'favicon-bolt'],
  'framesnap': ['clipy', 'recordsnap', 'tts-bolt', 'audiosnap', 'subtitles-bolt', 'klipy'],
  'cleansnap': ['pastesnap', 'compresssnap', 'backgroundremover', 'qr-bolt', 'cropsnap', 'gif-bolt'],
  'klipy': ['clipy', 'recordsnap', 'tts-bolt', 'audiosnap', 'subtitles-bolt', 'framesnap'],
  'clip-flow': ['twitchbolt', 'kickbolt', 'socialbolt'],
};
