import { Project, ProjectCategory, Language, LanguageCode } from './types';

export const TOOL_FAVICONS: Record<string, string> = {
  clipy: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'><path fill='%239146ff' d='M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V11h20v8z'/><g transform='rotate(-25 4 11)'><path fill='%237c3aed' d='M22 11V8a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v3h20z'/><path fill='white' opacity='0.6' d='m6.7 6 2.7 5h-1.5l-2.7-5h1.5zm5 0 2.7 5h-1.5l-2.7-5h1.5zm5 0 2.7 5h-1.5l-2.7-5h1.5z'/></g></svg>",
  twitchbolt: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%239146ff'><polygon points='13 2 3 14 12 14 11 22 21 10 12 10 13 2'/></svg>",
  kickbolt: "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%2353fc18'><polygon points='13 2 3 14 12 14 11 22 21 10 12 10 13 2'/></svg>",
  formatflow: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="%2338bdf8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m17 7 3 3-3 3M7 17l-3-3 3-3"/><path d="M3 14h11a4 4 0 0 0 4-4V7M21 10H10a4 4 0 0 0-4 4v3"/></svg>',
  pastesnap: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="%236366f1" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="9" cy="9" r="2"/><path d="m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"/></svg>',
  compresssnap: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="%2306b6d4" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M7 3.5l5 4.5 5-4.5"/><path d="M5 12h14"/><path d="M7 20.5l5-4.5 5 4.5"/></svg>',
  backgroundremover: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="%23ec4899" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="6" cy="6" r="3"/><circle cx="6" cy="18" r="3"/><line x1="9.8" y1="8.2" x2="21" y2="19"/><line x1="9.8" y1="15.8" x2="21" y2="5"/></svg>',
  'pdf-flow': 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="%23ef4444" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/><path d="M9 15h1a1.5 1.5 0 0 0 0-3H9v6"/><path d="M12 12v6h1a2 2 0 0 0 0-4h-1"/></svg>',
  recordsnap: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="%23f59e0b" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><circle cx="12" cy="12" r="3" fill="%23f59e0b"/></svg>',
  'qr-bolt': 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="%2310b981" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="8" height="8" x="3" y="3" rx="1"/><rect width="8" height="8" x="13" y="3" rx="1"/><rect width="8" height="8" x="3" y="13" rx="1"/><rect width="3" height="3" x="14" y="14"/><rect width="3" height="3" x="18" y="18"/><rect width="3" height="3" x="14" y="18"/><rect width="3" height="3" x="18" y="14"/></svg>',
  codecard: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="%236366f1" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="18" height="18" x="3" y="3" rx="2" ry="2"/><path d="m10 10-2 2 2 2M14 14l2-2-2-2"/></svg>',
  cropsnap: 'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="%23f43f5e" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M6 2v14a2 2 0 0 0 2 2h14M18 22V8a2 2 0 0 0-2-2H2"/></svg>',
  'css-designer': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%238b5cf6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='10'/><circle cx='12' cy='6' r='2' fill='%23ec4899'/><circle cx='6' cy='12' r='2' fill='%233b82f6'/><circle cx='18' cy='12' r='2' fill='%2310b981'/><circle cx='12' cy='18' r='2' fill='%23f59e0b'/></svg>",
  'json-flow': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%2310b981' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='18' height='18' rx='2' ry='2'/><line x1='9' y1='9' x2='15' y2='9'/><line x1='9' y1='13' x2='15' y2='13'/><line x1='9' y1='17' x2='13' y2='17'/></svg>",
  'socialbolt': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%236366f1' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4'/><polyline points='7 10 12 15 17 10'/><line x1='12' y1='15' x2='12' y2='3'/></svg>",
  'tts-bolt': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23f59e0b' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polygon points='11 5 6 9 2 9 2 15 6 15 11 19 11 5'/><path d='M19.07 4.93a10 10 0 0 1 0 14.14M15.54 8.46a5 5 0 0 1 0 7.07'/></svg>",
  'gif-bolt': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23d946ef' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='18' height='18' rx='2' ry='2'/><circle cx='8.5' cy='8.5' r='1.5'/><polyline points='21 15 16 10 5 21'/></svg>",
  'audiosnap': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23f43f5e' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z'/><path d='M19 10v2a7 7 0 0 1-14 0v-2'/><line x1='12' x2='12' y1='19' y2='22'/></svg>",
  'watermark-snap': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23f59e0b' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M12 2H2v10l9.29 9.29c.39.39 1.02.39 1.41 0l7.59-7.59c.39-.39.39-1.02 0-1.41L12 2z'/><path d='M7 7h.01'/></svg>",
  'favicon-bolt': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%233b82f6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect width='20' height='20' x='2' y='2' rx='2'/><path d='M2 8h20'/><circle cx='6' cy='5' r='1'/><circle cx='10' cy='5' r='1'/></svg>",
  'exif-clear': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%2310b981' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z'/><path d='m9 11 2 2 4-4'/></svg>",
  'meme-bolt': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23d946ef' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='12' cy='12' r='10'/><path d='M8 14s1.5 2 4 2 4-2 4-2'/><line x1='9' y1='9' x2='9.01' y2='9'/><line x1='15' y1='9' x2='15.01' y2='9'/></svg>",
  'wordflow': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%2314b8a6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M12 20h9'/><path d='M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z'/></svg>",
  'markdown-live': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%238b5cf6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='18' height='18' rx='2'/><path d='M7 15V9l3 3 3-3v6M17 11l2 2 2-2M19 9v6'/></svg>",
  'hash-bolt': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%230ea5e9' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='11' width='18' height='11' rx='2' ry='2'/><path d='M7 11V7a5 5 0 0 1 10 0v4'/></svg>",
  'zip-flow': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23f59e0b' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z'/><polyline points='3.27 6.96 12 12.01 20.73 6.96'/><line x1='12' y1='22.08' x2='12' y2='12'/></svg>",
  'regex-flow': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23d946ef' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='4' y1='6' x2='14' y2='6'/><line x1='4' y1='10' x2='10' y2='10'/><line x1='4' y1='14' x2='8' y2='14'/><circle cx='16' cy='14' r='5'/><line x1='19.5' y1='17.5' x2='23' y2='21'/></svg>",
  'lottie-viewer': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%236366f1' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><rect x='3' y='3' width='18' height='18' rx='2' ry='2'/><polygon points='10 8 16 12 10 16 10 8'/></svg>",
  'svg-optimizer': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%2306b6d4' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M12 2L2 22h20L12 2z'/><circle cx='12' cy='2' r='2' fill='%2306b6d4'/><circle cx='2' cy='22' r='2' fill='%2306b6d4'/><circle cx='22' cy='22' r='2' fill='%2306b6d4'/></svg>",
  'graph-flow': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23f59e0b' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><line x1='18' y1='20' x2='18' y2='10'/><line x1='12' y1='20' x2='12' y2='4'/><line x1='6' y1='20' x2='6' y2='14'/><line x1='2' y1='20' x2='22' y2='20'/></svg>",
  'url-bolt': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%2310b981' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><path d='M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71'/><path d='M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71'/></svg>",
  'clip-flow': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%238b5cf6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='6' cy='6' r='3'/><circle cx='6' cy='18' r='3'/><line x1='20' y1='4' x2='8.12' y2='15.88'/><line x1='14.47' y1='14.48' x2='20' y2='20'/><line x1='8.12' y1='8.12' x2='12' y2='12'/></svg>",
  'jwt-bolt': "data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%238b5cf6' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><circle cx='7' cy='15' r='4'/><path d='M10.85 12.15 19 4'/><path d='m18 5 3 3'/><path d='m15 8 3 3'/><path d='M3 21l3-3'/></svg>",
  default: "/icon.svg"
};

export const TOOL_THEME_COLORS: Record<string, string> = {
  clipy: "#9146ff",
  twitchbolt: "#7c3aed",
  kickbolt: "#53fc18",
  formatflow: "#38bdf8",
  pastesnap: "#6366f1",
  compresssnap: "#06b6d4",
  backgroundremover: "#ec4899",
  'pdf-flow': "#ef4444",
  recordsnap: "#f59e0b",
  'qr-bolt': "#10b981",
  codecard: "#6366f1",
  cropsnap: "#f43f5e",
  'css-designer': "#8b5cf6",
  'json-flow': "#10b981",
  'socialbolt': "#6366f1",
  'tts-bolt': "#f59e0b",
  'gif-bolt': "#d946ef",
  'audiosnap': "#f43f5e",
  'drawsnap': "#a855f7",
  'diffsnap': "#06b6d4",
  'watermark-snap': "#f59e0b",
  'favicon-bolt': "#3b82f6",
  'exif-clear': "#10b981",
  'meme-bolt': "#d946ef",
  'wordflow': "#14b8a6",
  'markdown-live': "#8b5cf6",
  'hash-bolt': "#0ea5e9",
  'zip-flow': "#f59e0b",
  'regex-flow': "#d946ef",
  'lottie-viewer': "#6366f1",
  'svg-optimizer': "#06b6d4",
  'graph-flow': "#f59e0b",
  'url-bolt': "#10b981",
  'base64-bolt': "#3b82f6",
  'clip-flow': "#8b5cf6",
  'jwt-bolt': "#8b5cf6",
  default: "#060609"
};

export const LANGUAGES: Language[] = [
  { code: 'en', label: 'English', name: 'English' },
  { code: 'es', label: 'Español', name: 'Español' },
  { code: 'hi', label: 'Hindi', name: 'Hindi' },
  { code: 'de', label: 'Deutsch', name: 'Deutsch' },
  { code: 'fr', label: 'Français', name: 'Français' },
  { code: 'pt', label: 'Português', name: 'Português' },
  { code: 'ru', label: 'Русский', name: 'Русский' },
  { code: 'ja', label: '日本語', name: '日本語' },
  { code: 'zh', label: '中文', name: '中文' },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: '1',
    name: 'Clipy',
    slug: 'clipy',
    description: 'A powerful tool to hunt, discover, and organize your favorite clips and videos.',
    category: ProjectCategory.VIDEO_AUDIO,
    tags: ['Video', 'Search', 'Clips', 'Tools'],
    icon: 'Film',
    color: 'bg-gradient-to-br from-indigo-500 to-purple-600'
  },
  {
    id: '2',
    name: 'TwitchBolt',
    slug: 'twitchbolt',
    description: 'Fast and easy Twitch clip downloader. Save your favorite moments instantly.',
    category: ProjectCategory.SOCIAL_DOWNLOADS,
    tags: ['Twitch', 'Download', 'Video', 'Clips'],
    icon: 'Download',
    color: 'bg-gradient-to-br from-violet-600 to-fuchsia-600'
  },
  {
    id: '3',
    name: 'FormatFlow',
    slug: 'formatflow',
    description: 'A powerful online tool to convert images, audio, and documents instantly.',
    category: ProjectCategory.DATA_CONVERSION,
    tags: ['Converter', 'Images', 'Audio', 'Tools'],
    icon: 'Repeat',
    color: 'bg-gradient-to-br from-emerald-500 to-teal-500'
  },
  {
    id: '4',
    name: 'PasteSnap',
    slug: 'pastesnap',
    description: 'Instantly paste your screenshots and images to download them in high quality. No login required.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Image', 'Download', 'Utility', 'Quick'],
    icon: 'Image',
    color: 'bg-gradient-to-br from-orange-500 to-red-600'
  },
  {
    id: '5',
    name: 'KickBolt',
    slug: 'kickbolt',
    description: 'Fast and easy Kick clip downloader. Save your favorite moments instantly.',
    category: ProjectCategory.SOCIAL_DOWNLOADS,
    tags: ['Kick', 'Download', 'Video', 'Clips'],
    icon: 'Download',
    color: 'bg-gradient-to-br from-green-500 to-emerald-600'
  },
  {
    id: '6',
    name: 'CompressSnap',
    slug: 'compresssnap',
    description: 'Compress and optimize your images (JPG, PNG, WebP) locally and instantly in your browser.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Image', 'Compress', 'WebP', 'Optimize'],
    icon: 'Image',
    color: 'bg-gradient-to-br from-cyan-500 to-blue-600'
  },
  {
    id: '7',
    name: 'Background Remover',
    slug: 'backgroundremover',
    description: 'Remove backgrounds from images locally and automatically with AI.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['AI', 'Image', 'Background', 'Remove'],
    icon: 'Image',
    color: 'bg-gradient-to-br from-fuchsia-500 to-pink-600'
  },
  {
    id: '8',
    name: 'PDFFlow',
    slug: 'pdf-flow',
    description: 'Merge, split, rotate, and convert documents or images to PDF locally in your browser.',
    category: ProjectCategory.DOCUMENT_PDF,
    tags: ['PDF', 'Merge', 'Split', 'Convert'],
    icon: 'FileText',
    color: 'bg-gradient-to-br from-red-500 to-rose-600'
  },
  {
    id: '9',
    name: 'RecordSnap',
    slug: 'recordsnap',
    description: 'Record your screen, webcam, or both simultaneously entirely in your browser.',
    category: ProjectCategory.VIDEO_AUDIO,
    tags: ['Screen', 'Webcam', 'Record', 'Video'],
    icon: 'Video',
    color: 'bg-gradient-to-br from-amber-500 to-orange-600'
  },
  {
    id: '10',
    name: 'QRBolt',
    slug: 'qr-bolt',
    description: 'Generate styled, high-quality QR codes with gradients, custom shapes, and center logos 100% locally.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['QR', 'Creator', 'Design', 'WiFi'],
    icon: 'QrCode',
    color: 'bg-gradient-to-br from-emerald-500 to-teal-600'
  },
  {
    id: '11',
    name: 'CodeCard',
    slug: 'codecard',
    description: 'Convert your code snippets into beautiful, sharing-ready screenshot cards with custom styles 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Code', 'Share', 'Developer', 'Screenshot'],
    icon: 'Code',
    color: 'bg-gradient-to-br from-indigo-500 to-violet-600'
  },
  {
    id: '12',
    name: 'CropSnap',
    slug: 'cropsnap',
    description: 'Crop, resize, rotate, and flip images with customizable presets and quality control 100% locally.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Crop', 'Resize', 'Rotate', 'Image'],
    icon: 'Crop',
    color: 'bg-gradient-to-br from-rose-500 to-red-600'
  },
  {
    id: '13',
    name: 'CSS Designer',
    slug: 'css-designer',
    description: 'Create and generate custom modern CSS styles like glassmorphism, shadows, gradients and fancy borders 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['CSS', 'Design', 'Tailwind', 'Utility'],
    icon: 'Palette',
    color: 'bg-gradient-to-br from-violet-600 to-indigo-700'
  },
  {
    id: '14',
    name: 'JSONFlow',
    slug: 'json-flow',
    description: 'Format, validate, explore and convert JSON data in the browser 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['JSON', 'Formatter', 'Converter', 'Developer'],
    icon: 'Code',
    color: 'bg-gradient-to-br from-emerald-600 to-teal-700'
  },
  {
    id: '15',
    name: 'SocialBolt',
    slug: 'socialbolt',
    description: 'Download TikTok videos without watermark, Instagram Reels, and YouTube Shorts 100% locally.',
    category: ProjectCategory.SOCIAL_DOWNLOADS,
    tags: ['Video', 'Download', 'TikTok', 'Instagram'],
    icon: 'Zap',
    color: 'bg-gradient-to-br from-indigo-500 to-pink-600'
  },
  {
    id: '16',
    name: 'TTSBolt',
    slug: 'tts-bolt',
    description: 'Convert text to natural speech and download it as an MP3 file 100% locally.',
    category: ProjectCategory.VIDEO_AUDIO,
    tags: ['Audio', 'Speech', 'TTS', 'Converter'],
    icon: 'Volume2',
    color: 'bg-gradient-to-br from-amber-500 to-orange-600'
  },
  {
    id: '17',
    name: 'GIFBolt',
    slug: 'gif-bolt',
    description: 'Convert videos and image sequences into optimized animated GIFs 100% locally.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Video', 'Images', 'GIF', 'Optimize'],
    icon: 'Images',
    color: 'bg-gradient-to-br from-fuchsia-500 to-purple-600'
  },
  {
    id: '18',
    name: 'AudioSnap',
    slug: 'audiosnap',
    description: 'Record microphone audio, trim silence, and download as WAV or native compressed files 100% locally.',
    category: ProjectCategory.VIDEO_AUDIO,
    tags: ['Audio', 'Record', 'Trim', 'Utility'],
    icon: 'Music',
    color: 'bg-gradient-to-br from-rose-500 to-red-600'
  },
  {
    id: '19',
    name: 'DrawSnap',
    slug: 'drawsnap',
    description: 'An interactive digital whiteboard to sketch ideas, draw vector shapes, and export creations as PNG or SVG 100% locally.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Draw', 'Whiteboard', 'Creative', 'Vector'],
    icon: 'PenTool',
    color: 'bg-gradient-to-br from-purple-500 to-indigo-600'
  },
  {
    id: '20',
    name: 'DiffSnap',
    slug: 'diffsnap',
    description: 'Compare two text files or code snippets and inspect additions, deletions, and differences side-by-side or unified 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Compare', 'Diff', 'Code', 'Developer'],
    icon: 'GitCompare',
    color: 'bg-gradient-to-br from-cyan-500 to-blue-600'
  },
  {
    id: '21',
    name: 'WatermarkSnap',
    slug: 'watermark-snap',
    description: 'Add text or logo watermarks to multiple images simultaneously. Process all files locally inside your browser.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Watermark', 'Batch', 'Image', 'Branding'],
    icon: 'Tag',
    color: 'bg-gradient-to-br from-amber-500 to-orange-600'
  },
  {
    id: '22',
    name: 'FaviconBolt',
    slug: 'favicon-bolt',
    description: 'Generate a complete package of standard website favicons from an image or emoji. Process all files locally inside your browser.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Favicon', 'Generator', 'Developer', 'Icon'],
    icon: 'Palette',
    color: 'bg-gradient-to-br from-blue-500 to-indigo-600'
  },
  {
    id: '23',
    name: 'EXIF Cleaner',
    slug: 'exif-clear',
    description: 'Inspect and strip EXIF, GPS, and metadata from images locally in your browser. Protect your privacy online.',
    category: ProjectCategory.SECURITY_CRYPTO,
    tags: ['Metadata', 'EXIF', 'Privacy', 'Image'],
    icon: 'Shield',
    color: 'bg-gradient-to-br from-emerald-500 to-teal-600'
  },
  {
    id: '24',
    name: 'MemeBolt',
    slug: 'meme-bolt',
    description: 'Create and generate custom memes from templates or your own images 100% locally in your browser.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Meme', 'Generator', 'Creative', 'Editor'],
    icon: 'Smile',
    color: 'bg-gradient-to-br from-fuchsia-500 to-purple-600'
  },
  {
    id: '25',
    name: 'WordFlow',
    slug: 'wordflow',
    description: 'An advanced word counter, character counter, readability analyzer, and text cleaning assistant 100% locally.',
    category: ProjectCategory.TEXT_UTILITIES,
    tags: ['Text', 'Analyzer', 'SEO', 'Writing'],
    icon: 'FileText',
    color: 'bg-gradient-to-br from-teal-500 to-cyan-600'
  },
  {
    id: '26',
    name: 'MarkdownLive',
    slug: 'markdown-live',
    description: 'A real-time visual Markdown editor and HTML previewer with style templates and PDF/HTML exporters 100% locally.',
    category: ProjectCategory.TEXT_UTILITIES,
    tags: ['Markdown', 'Editor', 'Writer', 'HTML'],
    icon: 'FileText',
    color: 'bg-gradient-to-br from-violet-500 to-indigo-600'
  },
  {
    id: '27',
    name: 'HashBolt',
    slug: 'hash-bolt',
    description: 'Calculate cryptographic hashes (MD5, SHA-1, SHA-256, SHA-512) for text and files 100% locally with checksum verification.',
    category: ProjectCategory.SECURITY_CRYPTO,
    tags: ['Cryptography', 'Hash', 'Developer', 'Security'],
    icon: 'Lock',
    color: 'bg-gradient-to-br from-sky-500 to-cyan-600'
  },
  {
    id: '28',
    name: 'ZipFlow',
    slug: 'zip-flow',
    description: 'Compress files into ZIP archives and extract files from ZIP archives 100% locally in your browser with real-time file tree visualization.',
    category: ProjectCategory.PRODUCTIVITY,
    tags: ['ZIP', 'Compress', 'Extract', 'Archive'],
    icon: 'FolderArchive',
    color: 'bg-gradient-to-br from-amber-500 to-orange-600'
  },
  {
    id: '29',
    name: 'RegexFlow',
    slug: 'regex-flow',
    description: 'An interactive regular expression builder, tester, and visualizer with real-time match highlighting and syntax breakdown 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Regex', 'Tester', 'Developer', 'Tool'],
    icon: 'Search',
    color: 'bg-gradient-to-br from-fuchsia-500 to-violet-600'
  },
  {
    id: '30',
    name: 'Lottie Viewer',
    slug: 'lottie-viewer',
    description: 'Render, inspect, and edit layer colors of Lottie JSON animations 100% locally in your browser with real-time playback controls.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Lottie', 'Animation', 'JSON', 'Design'],
    icon: 'Play',
    color: 'bg-gradient-to-br from-indigo-500 to-cyan-500'
  },
  {
    id: '31',
    name: 'SVG Optimizer',
    slug: 'svg-optimizer',
    description: 'Optimize, clean and compress SVG files 100% locally in your browser with real-time side-by-side previews and code formatting.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['SVG', 'Optimizer', 'Developer', 'Design'],
    icon: 'Maximize2',
    color: 'bg-gradient-to-br from-cyan-500 to-emerald-500'
  },
  {
    id: '32',
    name: 'GraphFlow',
    slug: 'graph-flow',
    description: 'Create beautiful charts from CSV data or manual input. Export as PNG, SVG, or PDF 100% locally in your browser.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Charts', 'Graphs', 'CSV', 'Data'],
    icon: 'BarChart3',
    color: 'bg-gradient-to-br from-amber-500 to-orange-600'
  },
  {
    id: '33',
    name: 'URLBolt',
    slug: 'url-bolt',
    description: 'Encode, decode, and parse URLs with query string breakdown and smart formatting 100% locally in your browser.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['URL', 'Encoder', 'Decoder', 'Developer'],
    icon: 'Link',
    color: 'bg-gradient-to-br from-emerald-500 to-teal-600'
  },
  {
    id: '34',
    name: 'Base64Bolt',
    slug: 'base64-bolt',
    description: 'Encode and decode Base64 strings and convert images to DataURL 100% locally in your browser.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Base64', 'Encoder', 'Image', 'DataURL'],
    icon: 'Binary',
    color: 'bg-gradient-to-br from-blue-500 to-indigo-600'
  },
  {
    id: '35',
    name: 'UUID Generator',
    slug: 'uuid-generator',
    description: 'Generate random UUIDs (v4) and named UUIDs (v5) in bulk up to 500 at once 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['UUID', 'GUID', 'Random', 'Generator'],
    icon: 'Fingerprint',
    color: 'bg-gradient-to-br from-violet-500 to-purple-600'
  },
  {
    id: '36',
    name: 'List Mixer',
    slug: 'list-mixer',
    description: 'Sort, reverse, shuffle, deduplicate, trim and clean lists of text 100% locally in your browser.',
    category: ProjectCategory.TEXT_UTILITIES,
    tags: ['List', 'Sorter', 'Shuffler', 'Dedupe'],
    icon: 'ListOrdered',
    color: 'bg-gradient-to-br from-orange-500 to-red-600'
  },
  {
    id: '37',
    name: 'HTML Sanitizer',
    slug: 'html-sanitizer',
    description: 'Clean and sanitize HTML code by removing scripts, styles, iframes and unwanted tags 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['HTML', 'Sanitizer', 'Cleaner', 'Security'],
    icon: 'ShieldCheck',
    color: 'bg-gradient-to-br from-cyan-500 to-teal-600'
  },
  {
    id: '38',
    name: 'ColorSnap',
    slug: 'colorsnap',
    description: 'Extract dominant colors and palettes from any image 100% locally in your browser.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Color', 'Palette', 'Design', 'Extractor'],
    icon: 'Palette',
    color: 'bg-gradient-to-br from-rose-500 to-pink-600'
  },
  {
    id: '39',
    name: 'Hex to RGB',
    slug: 'hex-to-rgb',
    description: 'Convert between HEX, RGB, HSL and CMYK color formats with opacity and contrast tools 100% locally.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Color', 'HEX', 'RGB', 'HSL'],
    icon: 'Palette',
    color: 'bg-gradient-to-br from-teal-500 to-cyan-600'
  },
  {
    id: '40',
    name: 'Aspect Ratio',
    slug: 'aspect-ratio',
    description: 'Calculate aspect ratios and proportional resolutions for video, images and screens 100% locally.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Ratio', 'Calculator', 'Resolution', 'Video'],
    icon: 'Ratio',
    color: 'bg-gradient-to-br from-lime-500 to-green-600'
  },
  {
    id: '41',
    name: 'UnitFlow',
    slug: 'unitflow',
    description: 'Convert units of measurement: length, weight, temperature, speed, volume and more 100% locally.',
    category: ProjectCategory.DATA_CONVERSION,
    tags: ['Unit', 'Converter', 'Measurement', 'Calculator'],
    icon: 'Ruler',
    color: 'bg-gradient-to-br from-blue-500 to-cyan-600'
  },
  {
    id: '42',
    name: 'SQLFlow',
    slug: 'sql-flow',
    description: 'Format, beautify and validate SQL queries with syntax highlighting 100% locally in your browser.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['SQL', 'Formatter', 'Validator', 'Database'],
    icon: 'Database',
    color: 'bg-gradient-to-br from-amber-500 to-yellow-600'
  },
  {
    id: '43',
    name: 'CronFlow',
    slug: 'cron-flow',
    description: 'Generate, translate and visualize cron expressions with human-readable descriptions 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Cron', 'Scheduler', 'DevOps', 'Translator'],
    icon: 'Clock',
    color: 'bg-gradient-to-br from-violet-500 to-fuchsia-600'
  },
  {
    id: '44',
    name: 'XML to JSON',
    slug: 'xml-json',
    description: 'Convert XML to JSON and JSON to XML instantly 100% locally in your browser.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['XML', 'JSON', 'Converter', 'Parser'],
    icon: 'FileCode',
    color: 'bg-gradient-to-br from-teal-500 to-emerald-600'
  },
  {
    id: '45',
    name: 'BinaryFlow',
    slug: 'binary-flow',
    description: 'Convert numbers and text between binary, hexadecimal, decimal and octal systems 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Binary', 'Hex', 'Decimal', 'Octal'],
    icon: 'Binary',
    color: 'bg-gradient-to-br from-blue-500 to-indigo-600'
  },
  {
    id: '46',
    name: 'MorseFlow',
    slug: 'morse-flow',
    description: 'Encode and decode Morse code with audio playback 100% locally in your browser.',
    category: ProjectCategory.TEXT_UTILITIES,
    tags: ['Morse', 'Audio', 'Encoder', 'Decoder'],
    icon: 'Radio',
    color: 'bg-gradient-to-br from-amber-500 to-orange-600'
  },
  {
    id: '47',
    name: 'EpochFlow',
    slug: 'epoch-flow',
    description: 'Convert Unix epoch timestamps to human-readable dates and vice versa 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Epoch', 'Timestamp', 'Unix', 'Converter'],
    icon: 'Clock',
    color: 'bg-gradient-to-br from-sky-500 to-cyan-600'
  },
  {
    id: '48',
    name: 'TimeBolt',
    slug: 'time-bolt',
    description: 'Convert time between world timezones with an interactive meeting planner 100% locally.',
    category: ProjectCategory.PRODUCTIVITY,
    tags: ['Timezone', 'Converter', 'Meeting', 'World Clock'],
    icon: 'Globe',
    color: 'bg-gradient-to-br from-teal-500 to-emerald-600'
  },
  {
    id: '49',
    name: 'Device Test',
    slug: 'device-test',
    description: 'Test your webcam, microphone, speakers and system info 100% locally in your browser.',
    category: ProjectCategory.NETWORK_SYSTEM,
    tags: ['Webcam', 'Microphone', 'Test', 'Device'],
    icon: 'Camera',
    color: 'bg-gradient-to-br from-rose-500 to-red-600'
  },
  {
    id: '50',
    name: 'LoremFlow',
    slug: 'lorem-flow',
    description: 'Generate Lorem Ipsum placeholder text by paragraphs, sentences or words 100% locally.',
    category: ProjectCategory.TEXT_UTILITIES,
    tags: ['Lorem', 'Generator', 'Placeholder', 'Text'],
    icon: 'AlignLeft',
    color: 'bg-gradient-to-br from-violet-500 to-purple-600'
  },
  {
    id: '51',
    name: 'Key Doctor',
    slug: 'key-doctor',
    description: 'Detect and display JavaScript keyboard event properties key, code and keyCode 100% locally.',
    category: ProjectCategory.DEVELOPER_TOOLS,
    tags: ['Keyboard', 'Events', 'Developer', 'Inspector'],
    icon: 'Keyboard',
    color: 'bg-gradient-to-br from-amber-500 to-yellow-600'
  },
  {
    id: '52',
    name: 'WhiteboardFlow',
    slug: 'whiteboard-flow',
    description: 'Organize notes in a virtual Kanban board with drag and drop 100% locally in your browser.',
    category: ProjectCategory.PRODUCTIVITY,
    tags: ['Kanban', 'Notes', 'Drag', 'Productivity'],
    icon: 'StickyNote',
    color: 'bg-gradient-to-br from-cyan-500 to-sky-600'
  },
  {
    id: '53',
    name: 'SubtitlesBolt',
    slug: 'subtitles-bolt',
    description: 'Convert subtitles between SRT, VTT and SBV formats 100% locally in your browser.',
    category: ProjectCategory.VIDEO_AUDIO,
    tags: ['Subtitles', 'SRT', 'VTT', 'Converter'],
    icon: 'Captions',
    color: 'bg-gradient-to-br from-blue-500 to-purple-600'
  },
  {
    id: '54',
    name: 'PassBolt',
    slug: 'passbolt',
    description: 'Generate secure passwords and test their strength with entropy analysis 100% locally.',
    category: ProjectCategory.SECURITY_CRYPTO,
    tags: ['Password', 'Generator', 'Security', 'Entropy'],
    icon: 'KeyRound',
    color: 'bg-gradient-to-br from-emerald-500 to-green-600'
  },
  {
    id: '55',
    name: 'WhoisBolt',
    slug: 'whois-bolt',
    description: 'Query DNS records (A, AAAA, MX, TXT, NS, CNAME, SOA) using DNS over HTTPS.',
    category: ProjectCategory.NETWORK_SYSTEM,
    tags: ['DNS', 'Lookup', 'Records', 'Domain'],
    icon: 'Search',
    color: 'bg-gradient-to-br from-indigo-500 to-blue-600'
  },
  {
    id: '56',
    name: 'FrameSnap',
    slug: 'framesnap',
    description: 'Step through any video frame by frame, scrub at different speeds and export the exact frame as a high-quality image 100% locally.',
    category: ProjectCategory.VIDEO_AUDIO,
    tags: ['Video', 'Frame', 'Extract', 'Image'],
    icon: 'Film',
    color: 'bg-gradient-to-br from-orange-500 to-amber-600'
  },
  {
    id: '57',
    name: 'CleanSnap',
    slug: 'cleansnap',
    description: 'Remove watermarks, logos and unwanted objects from images by painting over them with a brush, rectangle or circle — content-aware fill 100% locally.',
    category: ProjectCategory.IMAGE_DESIGN,
    tags: ['Watermark', 'Remove', 'Inpaint', 'Cleanup'],
    icon: 'Eraser',
    color: 'bg-gradient-to-br from-violet-500 to-purple-600'
  },
  {
    id: '58',
    name: 'Klipy',
    slug: 'klipy',
    description: 'Discover and watch the best Kick clips and live channels by category. Browse, save and export your favorite Kick moments.',
    category: ProjectCategory.VIDEO_AUDIO,
    tags: ['Kick', 'Clips', 'Live', 'Discover'],
    icon: 'Film',
    color: 'bg-gradient-to-br from-green-400 to-emerald-600'
  },
  {
    id: '59',
    name: 'ClipFlow',
    slug: 'clip-flow',
    description: 'Cut multiple clips of any length from Twitch VODs and live streams and export them as MP4 — no 60-second limit, 100% in your browser.',
    category: ProjectCategory.SOCIAL_DOWNLOADS,
    tags: ['Twitch', 'VOD', 'Clip', 'Editor'],
    icon: 'Scissors',
    color: 'bg-gradient-to-br from-violet-500 to-purple-600'
  },
  {
    id: '60',
    name: 'JWTBolt',
    slug: 'jwt-bolt',
    description: 'Decode and inspect JSON Web Tokens (JWT). Visualize header, payload and signature with live expiry validation 100% locally in your browser.',
    category: ProjectCategory.SECURITY_CRYPTO,
    tags: ['JWT', 'Token', 'Decoder', 'Security'],
    icon: 'KeyRound',
    color: 'bg-gradient-to-br from-violet-500 to-fuchsia-600'
  }
];
